# Generated by Django 5.0 on 2023-12-23 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="chat_slug",
            new_name="slug",
        ),
    ]
