# Generated by Django 5.0 on 2023-12-23 19:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0002_rename_chat_slug_room_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ("-date_added",),
                "verbose_name": "Сообщения",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="messages",
            options={
                "ordering": ("-message_id", "-date_time"),
                "verbose_name": "Голубиная почта",
                "verbose_name_plural": "Почта",
            },
        ),
        migrations.AlterModelOptions(
            name="resume",
            options={
                "ordering": ("-date_time", "title"),
                "verbose_name": "Резюме",
                "verbose_name_plural": "Резюме",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ("name",),
                "verbose_name": "Комнаты",
                "verbose_name_plural": "Комнаты",
            },
        ),
        migrations.AlterModelOptions(
            name="vacancyrequests",
            options={
                "ordering": ("-title", "resume"),
                "verbose_name": "Отклики на вакансии",
                "verbose_name_plural": "Отклики на вакансии",
            },
        ),
    ]
